default:
    image: rust:1.49.0 # update `run-tests`
    before_script:
        - export PATH=$PATH:/root/.cargo/bin/
        - rustup component add clippy
        - rustup component add rustfmt

check-formatting:
    stage: test
    image: rust:latest
    script:
        - cargo +stable fmt -- --check
    only:
        changes:
            - "src/**/*"
            - "examples/**/*"
            - Cargo.toml
            - .gitlab-ci.yml
        refs:
            - branches
            - merge_requests

run-clippy:
    stage: test
    image: rust:latest
    script:
        - cargo +stable clippy --target-dir=../target --examples --no-default-features --features "tls" -- -D warnings
        - cargo +stable clippy --target-dir=../target --examples --no-default-features --features "rustls" -- -D warnings
        - cargo +stable clippy --target-dir=../target --examples --features "proxy" -- -D warnings
    only:
        changes:
            - "src/**/*"
            - "examples/**/*"
            - Cargo.toml
            - .gitlab-ci.yml
            - clippy.toml
        refs:
            - branches
            - merge_requests

run-tests:
    stage: test
    script:
        - cargo +1.49.0 test --target-dir=../target --features="proxy"
    only:
        changes:
            - "src/**/*"
            - "examples/**/*"
            - Cargo.toml
            - .gitlab-ci.yml
        refs:
            - branches
            - merge_requests

pages:
    stage: docs
    image: rust:latest
    script:
        - cargo +stable doc --release --no-deps --target-dir=../target
        - mv ../target/doc ./public
        - mv ./public/tbot/* ./public/
        - cd ./public
        - grep -rl "../tbot" * | while read f; do sed -i -e 's#\.\./tbot/#\.\./#g' "$f"; done
        - sed -i 's#return\[displayPath,href\]#return\[displayPath,href.replace("\.\./tbot/", "\.\./")\]#g' main.js
    artifacts:
        paths:
            - public
    only:
        changes:
            - "src/**/*"
            - Cargo.toml
            - .gitlab-ci.yml
        refs:
            - master

stages:
    - test
    - docs
